insert into skill (name, usage) values ( 'java',0),
                                       ('kotlin', 0),
                                       ('node.js', 0),
                                       ('python', 0),
                                       ('c', 0),
                                       ('c++', 0),
                                       ('c#', 0),
                                       ('spring', 0),
                                       ('spring boot', 0),
                                       ('jpa', 0),
                                       ('queryDsl', 0),
                                       ('jpql', 0),
                                       ('golang', 0),
                                       ('php', 0),
                                       ('html', 0),
                                       ('css', 0),
                                       ('thymeleaf', 0),
                                       ('jquery', 0),
                                       ('react', 0),
                                       ('vue.js', 0),
                                       ('typescript', 0),
                                       ('javascript', 0),
                                       ('mysql', 0),
                                       ('mybatis', 0),
                                       ('postgresql', 0),
                                       ('aws', 0),
                                       ('jenkins', 0),
                                       ('kubernetes', 0),
                                       ('docker', 0),
                                       ('linux', 0),
                                       ('redis', 0),
                                       ('kafka',0);
